# 2024-12-27

In [2]:
from decorator import append

number= [1,2,3,4,5]

arra = [x**2 for x in number if x % 2 == 0]
print(arra)

[4, 16]


In [29]:
import numpy as np
a_list = [1,2,'3',4,5]
arr = np.array(a_list)
print(arr)
print(type(arr))
arr1 = np.arange(1, 10, 2)
print(arr1)

arr2 = np.zeros(20, dtype=int)
arr3 = np.zeros((2,10))
arr4 = np.reshape(arr2, (2, 10))
print(arr2)
print(arr3)
print(arr4)


['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>
[1 3 5 7 9]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [48]:
arr5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr6 = np.array([[1,2,3, 4,5,6,7,8]])
print(arr5)
print(arr5.shape)
print(arr5.reshape(3,3))
print(arr5.reshape(3,3).T)
print(arr6.reshape(2,4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3 4]
 [5 6 7 8]]


In [54]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

answer = []
for i in data:
  answer.append(2 * i)
answer

c = np.array([[0, 1, 2], [3, 4, 5]])

# 행의 갯수
print(len(c))

# 열의 갯수
print(len(c[0]))

2
3


In [62]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0][0])
print(a[0][1])
print(a[1][2])
print(a[0])
print(a[:, 1])
print(a[:2, :2])


0
1
5
[0 1 2]
[1 4]
[[0 1]
 [3 4]]


In [71]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [114]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
# print(a[idx])
answer = a % 2 == 0
print(answer)
a[a % 2 == 0]

b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(b[:, [0, 3]])
print(b[:, [True, False, False, True]])


[ True False  True False  True False  True False  True False]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [129]:
c = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(c[[2, 0, 1], :])

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [145]:
# 판다스 - 데이터를 조작/분석하기 위한 라이브러리, 다양한 데이터 분석 함수 제공, 행과 열로 이루어진 데이터 객체를 만들고 다룰 수 있다.
import pandas as pd

# pd.DataFrame(a)

series = pd.Series([3, -5, 7, 4])
# print(series)
# print(type(series))

s = pd.Series([3, -5, 7, 4], index = ['a', 'b', 'c', 'd'])
print(s)
print(s['a'])
print(s[['a', 'c']])
s.index
s.values

print(s['a'])

a    3
b   -5
c    7
d    4
dtype: int64
3
a    3
c    7
dtype: int64
3


In [155]:
df = pd.DataFrame({'Division':['부산광역시', '전라남도', '강원도']
                    , 'Code': ['051', '061', '033']
                    , 'Population': [3364358, 1840921, 1535530]})
display(df)
print(df)
print(df['Division'])
print(df[['Division', 'Population']])
print(df.Division)
print(df.Population)
df.index
df.columns


Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

  Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530
0    부산광역시
1     전라남도
2      강원도
Name: Division, dtype: object
  Division  Population
0    부산광역시     3364358
1     전라남도     1840921
2      강원도     1535530
0    부산광역시
1     전라남도
2      강원도
Name: Division, dtype: object
0    3364358
1    1840921
2    1535530
Name: Population, dtype: int64


Index(['Division', 'Code', 'Population'], dtype='object')

In [165]:
pd.options.display.float_format = '{:.0f}'.format
df = pd.read_csv('heroes.csv')
df.info()
df.describe()
df['국적'].unique()
df['국적'].value_counts()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [282]:
# df['나이'].sort_values(ascending=True)
# df['나이'].nlargest(10)
# df.nlargest(3, '나이')
# df.나이.sort_values(ascending=False)
# df[0:2]
# df.iloc[3] # 하나의 행만 가져옴
# df.iloc[[1, 3, 4]] # 하나의 행만 가져옴

# df.iloc[:5, :3]
df2 = df.copy()
df2.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

# df2.loc['a': 'b']
# df2.loc['a':'b', '이름':'직업']
# df.isnull().sum()
# df[df.재산.isnull()]
# df[(df.나이 > 30) & (df.나이 < 50)]
# df.loc[(df.나이 > 30) & (df.나이 < 50), '이름':'직업']
# df.sort_values('키', ascending=False)


# '기뮤림', 1, '학생', '대한민국', 170, '100000000000000', 100
# df2.전투력 -=5


TypeError: concat() takes 1 positional argument but 7 were given

In [323]:
# df2.drop(index='a', inplace=True) # inplace는 대체 하겠다는 의미 그래서 진짜 삭제됨
# df2.drop(columns='키') # inplace는 대체 하겠다는 의미 그래서 진짜 삭제됨
# df2.drop(index='a')
# df2.dropna(axis = 0, inplace=True)
# df2.dropna(axis = 0)
df2.fillna(0)
# df2.fillna(method='bfill')
# df2
df2.재산.mean()

np.float64(2578000120.0)